# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardItemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cardItem(object):
    def setupUi(self, cardItem):
        cardItem.setObjectName("cardItem")
        cardItem.resize(650, 350)
        cardItem.setMinimumSize(QtCore.QSize(650, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(cardItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(cardItem)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.photo_label = QtWidgets.QLabel(self.groupBox)
        self.photo_label.setGeometry(QtCore.QRect(10, 10, 251, 321))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.photo_label.setFont(font)
        self.photo_label.setText("")
        self.photo_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.photo_label.setObjectName("photo_label")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(280, 10, 341, 321))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(cardItem)
        QtCore.QMetaObject.connectSlotsByName(cardItem)

    def retranslateUi(self, cardItem):
        _translate = QtCore.QCoreApplication.translate
        cardItem.setWindowTitle(_translate("cardItem", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cardItem = QtWidgets.QWidget()
    ui = Ui_cardItem()
    ui.setupUi(cardItem)
    cardItem.show()
    sys.exit(app.exec_())
