# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogWidget(object):
    def setupUi(self, catalogWidget):
        catalogWidget.setObjectName("catalogWidget")
        catalogWidget.resize(330, 482)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(catalogWidget.sizePolicy().hasHeightForWidth())
        catalogWidget.setSizePolicy(sizePolicy)
        catalogWidget.setMinimumSize(QtCore.QSize(330, 480))
        self.verticalLayout = QtWidgets.QVBoxLayout(catalogWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(catalogWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 460))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.photo_label = QtWidgets.QLabel(self.groupBox)
        self.photo_label.setGeometry(QtCore.QRect(10, 10, 291, 331))
        self.photo_label.setMinimumSize(QtCore.QSize(291, 331))
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")
        self.name_label = QtWidgets.QLabel(self.groupBox)
        self.name_label.setGeometry(QtCore.QRect(10, 340, 250, 41))
        self.name_label.setMinimumSize(QtCore.QSize(250, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.price_label = QtWidgets.QLabel(self.groupBox)
        self.price_label.setGeometry(QtCore.QRect(10, 380, 250, 22))
        self.price_label.setMinimumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.price_label.setFont(font)
        self.price_label.setObjectName("price_label")
        self.card_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.card_pushButton.setGeometry(QtCore.QRect(10, 420, 141, 35))
        self.card_pushButton.setMinimumSize(QtCore.QSize(140, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.card_pushButton.setFont(font)
        self.card_pushButton.setStyleSheet("background-color: red;\n"
"border: none;\n"
"border-radius: 17px;")
        self.card_pushButton.setObjectName("card_pushButton")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(catalogWidget)
        QtCore.QMetaObject.connectSlotsByName(catalogWidget)

    def retranslateUi(self, catalogWidget):
        _translate = QtCore.QCoreApplication.translate
        catalogWidget.setWindowTitle(_translate("catalogWidget", "Form"))
        self.name_label.setText(_translate("catalogWidget", "Наименование товара"))
        self.price_label.setText(_translate("catalogWidget", "Стоимость"))
        self.card_pushButton.setText(_translate("catalogWidget", "В корзину"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    catalogWidget = QtWidgets.QWidget()
    ui = Ui_catalogWidget()
    ui.setupUi(catalogWidget)
    catalogWidget.show()
    sys.exit(app.exec_())
