# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart-mirror2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.takePhotoButton = QtWidgets.QPushButton(self.centralwidget)
        self.takePhotoButton.setGeometry(QtCore.QRect(580, 570, 130, 130))
        self.takePhotoButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 0, 0, 0.2);\n"
"}")
        self.takePhotoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/UI-images/photo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.takePhotoButton.setIcon(icon)
        self.takePhotoButton.setIconSize(QtCore.QSize(200, 200))
        self.takePhotoButton.setObjectName("takePhotoButton")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(40, 360, 81, 141))
        self.leftButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 0, 0, 0.0);\n"
"border: 0px solid red;\n"
"}")
        self.leftButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/UI-images/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon1)
        self.leftButton.setIconSize(QtCore.QSize(180, 180))
        self.leftButton.setObjectName("leftButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 960))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 731, 1011, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(150, 150))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(150, 150))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(200, 199))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(150, 150))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(150, 150))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.catalogButton = QtWidgets.QPushButton(self.centralwidget)
        self.catalogButton.setGeometry(QtCore.QRect(30, 590, 100, 100))
        self.catalogButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 0, 0, 0.2);\n"
"border: 1px solid red;\n"
"}")
        self.catalogButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/UI-images/catalog.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.catalogButton.setIcon(icon2)
        self.catalogButton.setIconSize(QtCore.QSize(100, 100))
        self.catalogButton.setObjectName("catalogButton")
        self.galleryButton = QtWidgets.QPushButton(self.centralwidget)
        self.galleryButton.setGeometry(QtCore.QRect(1140, 590, 100, 100))
        self.galleryButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 0, 0, 0.2);\n"
"border: 1px solid red;\n"
"}")
        self.galleryButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/UI-images/gallery.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.galleryButton.setIcon(icon3)
        self.galleryButton.setIconSize(QtCore.QSize(100, 100))
        self.galleryButton.setObjectName("galleryButton")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(1150, 360, 81, 141))
        self.rightButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 0, 0, 0.0);\n"
"border: 0px solid red;\n"
"}")
        self.rightButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/UI-images/arrow2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon4)
        self.rightButton.setIconSize(QtCore.QSize(180, 180))
        self.rightButton.setObjectName("rightButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 151, 100))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1150, 30, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.takePhotoButton.raise_()
        self.leftButton.raise_()
        self.horizontalLayoutWidget.raise_()
        self.catalogButton.raise_()
        self.galleryButton.raise_()
        self.rightButton.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
