# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogWindow(object):
    def setupUi(self, CatalogWindow):
        CatalogWindow.setObjectName("CatalogWindow")
        CatalogWindow.resize(725, 1176)
        CatalogWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(CatalogWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 45 pt \"Noto Sans\" ;\n"
"font-weight: bold;\n"
"color: black;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.fit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.fit_pushButton.setStyleSheet("border: none;")
        self.fit_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fit_pushButton.setIcon(icon)
        self.fit_pushButton.setIconSize(QtCore.QSize(70, 70))
        self.fit_pushButton.setObjectName("fit_pushButton")
        self.horizontalLayout_5.addWidget(self.fit_pushButton)
        self.card_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.card_pushButton.setStyleSheet("border: none;\n"
"")
        self.card_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card_pushButton.setIcon(icon1)
        self.card_pushButton.setIconSize(QtCore.QSize(85, 85))
        self.card_pushButton.setObjectName("card_pushButton")
        self.horizontalLayout_5.addWidget(self.card_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 25 pt \"Noto Sans\" ;\n"
"color: black;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(2)
        self.filter_pushButton.setFont(font)
        self.filter_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filter_pushButton.setStyleSheet("border: none;\n"
"font: 15 pt \"Noto Sans\" ;\n"
"color: black;\n"
"text-align: left;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filter_pushButton.setIcon(icon2)
        self.filter_pushButton.setIconSize(QtCore.QSize(22, 22))
        self.filter_pushButton.setObjectName("filter_pushButton")
        self.horizontalLayout.addWidget(self.filter_pushButton)
        self.sort_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(2)
        self.sort_pushButton.setFont(font)
        self.sort_pushButton.setStyleSheet("border: none;\n"
"font: 15 pt \"Noto Sans\" ;\n"
"color: black;\n"
"text-align: left;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sort_pushButton.setIcon(icon3)
        self.sort_pushButton.setIconSize(QtCore.QSize(28, 28))
        self.sort_pushButton.setObjectName("sort_pushButton")
        self.horizontalLayout.addWidget(self.sort_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 988))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        CatalogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CatalogWindow)
        QtCore.QMetaObject.connectSlotsByName(CatalogWindow)

    def retranslateUi(self, CatalogWindow):
        _translate = QtCore.QCoreApplication.translate
        CatalogWindow.setWindowTitle(_translate("CatalogWindow", "MainWindow"))
        self.label.setText(_translate("CatalogWindow", "Каталог"))
        self.label_2.setText(_translate("CatalogWindow", "Название подкаталога"))
        self.filter_pushButton.setText(_translate("CatalogWindow", " Фильтры"))
        self.sort_pushButton.setText(_translate("CatalogWindow", " Сортировка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CatalogWindow = QtWidgets.QMainWindow()
    ui = Ui_CatalogWindow()
    ui.setupUi(CatalogWindow)
    CatalogWindow.show()
    sys.exit(app.exec_())
